site_name: Aerodrome
site_url: https://ch4acko3.github.io/Aerodrome/
repo_url: https://github.com/CH4ACKO3/Aerodrome

docs_dir: docs/

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            概述: Overview
            快速入门: Get Started
            安装: Installation
            项目结构: Project Structure
            示例: Examples
            基础逻辑和类: Basics and Classes
            最简环境: Minimal Example

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 概述:
    - index.md
    - 快速入门:
      - 安装: get_started.md
      - 项目结构: project_structure.md
    - 示例:
      - 基础逻辑和类: basics.md
      - 最简环境: minimal_example.md
      - CartPole 和 DQN: cartpole_dqn.md
